//! Deep merge logic for Helm values.
//!
//! Merges user-supplied `spec.values` with MultiTool-injected values (e.g.,
//! OTel resource attributes). MultiTool keys take precedence over user keys,
//! while all non-conflicting user keys are preserved.
//!
//! Arrays are replaced entirely by the override (not concatenated), following
//! the same semantics as Helm's own values merge behavior.

use serde_json::Value;

/// Deep-merges `override_values` into `base`, returning the merged result.
///
/// - Objects are recursively merged: keys from `override_values` take
///   precedence, while keys only in `base` are preserved.
/// - Non-object values (arrays, strings, numbers, booleans, nulls) in
///   `override_values` replace the corresponding value in `base`.
/// - `null` in `override_values` replaces whatever is in `base`.
pub fn deep_merge(base: &Value, override_values: &Value) -> Value {
    match (base, override_values) {
        (Value::Object(base_map), Value::Object(override_map)) => {
            let mut merged = base_map.clone();
            for (key, override_val) in override_map {
                let merged_val = if let Some(base_val) = base_map.get(key) {
                    deep_merge(base_val, override_val)
                } else {
                    override_val.clone()
                };
                merged.insert(key.clone(), merged_val);
            }
            Value::Object(merged)
        }
        // Non-object override replaces base entirely.
        (_, override_val) => override_val.clone(),
    }
}

/// Merges user spec values with MultiTool-injected values.
///
/// `user_values` is `spec.values` from the HelmRelease CR.
/// `injected_values` is the overlay generated by MultiTool (e.g., OTel attrs).
///
/// Injected values take precedence over user values.
pub fn merge_helm_values(user_values: Option<&Value>, injected_values: &Value) -> Value {
    match user_values {
        Some(base) => deep_merge(base, injected_values),
        None => injected_values.clone(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;

    #[test]
    fn merge_disjoint_keys() {
        let base = json!({"a": 1});
        let over = json!({"b": 2});
        let result = deep_merge(&base, &over);
        assert_eq!(result, json!({"a": 1, "b": 2}));
    }

    #[test]
    fn override_takes_precedence() {
        let base = json!({"key": "old"});
        let over = json!({"key": "new"});
        let result = deep_merge(&base, &over);
        assert_eq!(result, json!({"key": "new"}));
    }

    #[test]
    fn nested_merge() {
        let base = json!({
            "outer": {
                "keep": "preserved",
                "replace": "old"
            }
        });
        let over = json!({
            "outer": {
                "replace": "new",
                "add": "added"
            }
        });
        let result = deep_merge(&base, &over);
        assert_eq!(
            result,
            json!({
                "outer": {
                    "keep": "preserved",
                    "replace": "new",
                    "add": "added"
                }
            })
        );
    }

    #[test]
    fn deeply_nested_merge() {
        let base = json!({
            "a": {
                "b": {
                    "c": "original",
                    "d": "kept"
                }
            }
        });
        let over = json!({
            "a": {
                "b": {
                    "c": "overridden"
                }
            }
        });
        let result = deep_merge(&base, &over);
        assert_eq!(
            result,
            json!({
                "a": {
                    "b": {
                        "c": "overridden",
                        "d": "kept"
                    }
                }
            })
        );
    }

    #[test]
    fn array_replacement() {
        let base = json!({"list": [1, 2, 3]});
        let over = json!({"list": [4, 5]});
        let result = deep_merge(&base, &over);
        assert_eq!(result, json!({"list": [4, 5]}));
    }

    #[test]
    fn null_override() {
        let base = json!({"key": "value"});
        let over = json!({"key": null});
        let result = deep_merge(&base, &over);
        assert_eq!(result, json!({"key": null}));
    }

    #[test]
    fn override_object_with_scalar() {
        let base = json!({"key": {"nested": "value"}});
        let over = json!({"key": "flat"});
        let result = deep_merge(&base, &over);
        assert_eq!(result, json!({"key": "flat"}));
    }

    #[test]
    fn override_scalar_with_object() {
        let base = json!({"key": "flat"});
        let over = json!({"key": {"nested": "value"}});
        let result = deep_merge(&base, &over);
        assert_eq!(result, json!({"key": {"nested": "value"}}));
    }

    #[test]
    fn empty_base() {
        let base = json!({});
        let over = json!({"key": "value"});
        let result = deep_merge(&base, &over);
        assert_eq!(result, json!({"key": "value"}));
    }

    #[test]
    fn empty_override() {
        let base = json!({"key": "value"});
        let over = json!({});
        let result = deep_merge(&base, &over);
        assert_eq!(result, json!({"key": "value"}));
    }

    #[test]
    fn merge_helm_values_with_none() {
        let injected = json!({"extraEnv": [{"name": "FOO", "value": "bar"}]});
        let result = merge_helm_values(None, &injected);
        assert_eq!(result, injected);
    }

    #[test]
    fn merge_helm_values_preserves_user_keys() {
        let user = json!({
            "replicaCount": 3,
            "image": {"tag": "v1.0"}
        });
        let injected = json!({
            "extraEnv": [{"name": "OTEL_RESOURCE_ATTRIBUTES", "value": "role=canary"}]
        });
        let result = merge_helm_values(Some(&user), &injected);
        assert_eq!(
            result,
            json!({
                "replicaCount": 3,
                "image": {"tag": "v1.0"},
                "extraEnv": [{"name": "OTEL_RESOURCE_ATTRIBUTES", "value": "role=canary"}]
            })
        );
    }

    #[test]
    fn merge_helm_values_injected_overrides_user() {
        let user = json!({
            "extraEnv": [{"name": "APP_ENV", "value": "prod"}]
        });
        let injected = json!({
            "extraEnv": [{"name": "OTEL_RESOURCE_ATTRIBUTES", "value": "role=canary"}]
        });
        let result = merge_helm_values(Some(&user), &injected);
        // Array override: injected replaces user's extraEnv.
        assert_eq!(
            result,
            json!({
                "extraEnv": [{"name": "OTEL_RESOURCE_ATTRIBUTES", "value": "role=canary"}]
            })
        );
    }

    #[test]
    fn integration_with_otel_overlay() {
        use crate::controller::otel::{DeploymentRole, otel_values_overlay};

        let user = json!({
            "replicaCount": 3,
            "service": {"port": 8080}
        });
        let otel = otel_values_overlay(DeploymentRole::Canary);
        let result = merge_helm_values(Some(&user), &otel);

        assert_eq!(result["replicaCount"], 3);
        assert_eq!(result["service"]["port"], 8080);

        let extra_env = result["extraEnv"].as_array().expect("extraEnv");
        assert_eq!(extra_env.len(), 1);
        assert_eq!(extra_env[0]["name"], "OTEL_RESOURCE_ATTRIBUTES");
        assert_eq!(extra_env[0]["value"], "multitool.io/deployment.role=canary");
    }
}
